name: "Trigger genshin-dictionary deployment"

on:
  check_run:
    types:
      - completed

jobs:
  trigger:
    if: ${{ github.event.check_run.name == 'Cloudflare Pages' && github.event.check_run.conclusion == 'success' && github.event.check_run.head_sha == github.sha }}
    timeout-minutes: 2
    runs-on: ubuntu-latest
    env:
      CFPAGES_REBUILD_HOOK: ${{ secrets.CFPAGES_REBUILD_HOOK }}

    steps:
      - name: Trigger genshin-dictionary deployment
        run: curl -sS -X POST "${CFPAGES_REBUILD_HOOK}"
